### ISSUE TITLE
Interactive API would be nice!

### ISSUE THREAD

**Issue by toyboot4e** [azu/license-generator#17]
We have to remember the `--author <my name>` argument every time we use `license-generator`.

If the tools asks us like this, it would be easier:

```
$ license-generator
license name: MIT
author name: super-cool-guy
==> generated! (./LICENSE)
$
```

**Comment by azu** [comment]
- [nexxeln/license-generator: Create licenses for your projects right from your terminal!](https://github.com/nexxeln/license-generator)
- [frectonz/license-gen: A license generator made with rust.](https://github.com/frectonz/license-gen)

These tools support this feature.

However, I am not really motivated by this feature.
This is because we want to keep the CLI as simple as possible.
(If you are working with a CLI such as [fzf](https://github.com/junegunn/fzf), we may need a function such as `license-generator --list` to return a list of licences.)
